### ISSUE TITLE
mdx not updated, plus a weird warning

### ISSUE THREAD

**Issue by sillyleo** [johno/gatsby-theme-documentation#108]
Hi, thank your for the work. But I encountered 2 issues and wan't sure if they are related.

1. `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()`

<img width="539" alt="image" src="https://user-images.githubusercontent.com/105896/65752988-8eb69e00-e140-11e9-8de6-613a5bd8e85f.png">

Seems like Sidenav can't use ref. But I don't know how to solve it.

2. mdx in docs not updating immediately: I have to `gatsby clean` and then `gatsby develop` to see the changes. Updating sidebar.mdx works fine, thought.

(Thanks again. I'm new to React and gatsby.)

**Comment by johno** [comment]
Thanks for reporting @sillyleo!

The MDX not updating was indeed a bug which I've now fixed and published. If you upgrade to the latest version of `gatsby-theme-documentation` it should now work. I'll dig into the warning a bit later as well.

**Comment by johno** [comment]
I've fixed the warning as well in version `0.0.27`. Thanks for opening this issue!
