### ISSUE TITLE
Margin on mobile

### ISSUE THREAD

**Issue by johnletey** [johno/gatsby-theme-documentation#64]
@johno As you may know, we're using this theme for our documentation at Learn Anything (here is our [repo](https://github.com/learn-anything/docs)) ... and we've noticed that there isn't any margins for the mobile view. Here is a screenshot:

<img src="https://user-images.githubusercontent.com/30328854/62826347-ce85ee00-bbb1-11e9-918a-7c2c52816821.jpg" width="200" />

Would love a fix for this 🙏

**Comment by rdela** [comment]
PR #79 has a fix for this, I pulled in relevant code from https://theme-ui.com
https://github.com/system-ui/theme-ui/blob/master/packages/docs/src/components/layout.js#L70

It pads the section with 16px on the sides no matter the width of the viewport. Thoughts?

**Comment by rdela** [comment]
Demo: https://gatsby-theme-documentation-git-fork-rdela-mobile-margin.johno1.now.sh/
