### ISSUE TITLE
Invalid hooks call + demo website is broken

### ISSUE THREAD

**Issue by kiastorm** [johno/gatsby-theme-documentation#99]
I just cloned this repo and am getting an error immediately after running gatsby develop

![image](https://user-images.githubusercontent.com/43898703/64668474-0cbc4900-d4a1-11e9-8218-061cb3f22c79.png)

**Comment by johno** [comment]
I've just pushed a commit that _should_ fix this. Somehow yarn resolution was breaking with the local version of react and the version that theme-ui brought along.

**Comment by johno** [comment]
This is now fixed, thanks for reporting!
